version: '2'
services:
  nginx:
     build:
      context: ./
      dockerfile: nginx.dockerfile
     working_dir: /srv/www
     network_mode: bridge
     links:
        - php
     ports:
       - 8080:80
     volumes_from:
        - php
  php:
     build:
      context: ./
      dockerfile: php.dockerfile
     working_dir: /srv/www
     network_mode: bridge
     links:
       - db
     volumes:
        - /srv/www
        - ./src/www:/srv/www
     env_file: env
  db:
     image: mysql
     command: --max_allowed_packet=1G --secure-file-priv=""
     network_mode: bridge
     environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: picpay
     volumes:
       - /srv/www
       - ./src/data:/srv/www/data