version: '2'
services:
  nginx:
     build:
      context: ./
      dockerfile: nginx.dockerfile
     working_dir: /srv/www
     network_mode: bridge
     env_file: env
     links:
        - php
     ports:
       - 80:80
     volumes_from:
        - php
  php:
     build: 
      context: ./
      dockerfile: php.dockerfile
     working_dir: /srv/www
     network_mode: bridge
     links:
        - db
     volumes:
        - /srv/www
        - ./src/www:/srv/www
     env_file: env
  db:
     image: mysql
     network_mode: bridge
     command: --max_allowed_packet=512M
     environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: picpay_users
