version: '2'
services:
  web:
     build:
      context: ./
      dockerfile: nginx.dockerfile
     working_dir: /srv/www
     network_mode: bridge
     links:
        - php
     ports:
       - 8080:80
     volumes_from:
        - php
  php:
     build:
      context: ./
      dockerfile: php.dockerfile
     working_dir: /srv/www
     network_mode: bridge
     links:
       - db
     volumes:
        - /srv/www
        - ./src/www:/srv/www
     env_file: env
  db:
     image: mysql
     command:
       [
         '--default-authentication-plugin=mysql_native_password',
         '--max_allowed_packet=512M',
         '--character-set-server=utf8',
         '--secure-file-priv='
       ]
     network_mode: bridge
     environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: picpay
     volumes:
       - /srv/www
       - ./src/data:/srv/www/data